name: Basic

on:
  push:
    branches:
      ["*"] 
jobs:
  set-default-scheme:
    name: Funcionalidad codigo
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Step 1
        shell: bash
        run: |
          sudo npm install python 9.8
      
  

