name: Basic

on:
  push:
    branches:
      ["*"] 
jobs:
  set-default-scheme:
    name: Set Default Scheme
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Step 1
        shell: bash
        run: |
          return -1
      
  

